apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPGroup
metadata:
  name: demo-tools
  namespace: toolhive-system
spec:
  description: Demo group for vMCP aggregation
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: fetch
  namespace: toolhive-system
  labels:
    demo.toolhive.stacklok.dev/vmcp-backend: "true"
spec:
  image: ghcr.io/stackloklabs/gofetch/server:1.0.3
  transport: streamable-http
  proxyPort: 8080
  mcpPort: 8080
  groupRef: demo-tools
  telemetry:
    openTelemetry:
      enabled: true
      endpoint: mcp-collector.observability:4318
      insecure: true
      serviceName: fetch-server
      metrics:
        enabled: true
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: osv
  namespace: toolhive-system
  labels:
    demo.toolhive.stacklok.dev/vmcp-backend: "true"
spec:
  image: ghcr.io/stackloklabs/osv-mcp/server:0.1.0
  transport: streamable-http
  proxyPort: 8080
  mcpPort: 8080
  groupRef: demo-tools
  telemetry:
    openTelemetry:
      enabled: true
      endpoint: mcp-collector.observability:4318
      insecure: true
      serviceName: osv-server
      metrics:
        enabled: true
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: oci-registry
  namespace: toolhive-system
  labels:
    demo.toolhive.stacklok.dev/vmcp-backend: "true"
spec:
  image: ghcr.io/stackloklabs/ocireg-mcp/server:0.1.0
  groupRef: demo-tools
  transport: streamable-http
  mcpPort: 8080
  proxyPort: 8080
  telemetry:
    openTelemetry:
      enabled: true
      endpoint: mcp-collector.observability:4318
      insecure: true
      serviceName: oci-registry-server
      metrics:
        enabled: true
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: context7
  namespace: toolhive-system
  labels:
    demo.toolhive.stacklok.dev/vmcp-backend: "true"
spec:
  image: ghcr.io/stacklok/dockyard/npx/context7:2.1.1
  groupRef: demo-tools
  transport: stdio
  proxyPort: 8080
  proxyMode: streamable-http
  telemetry:
    openTelemetry:
      enabled: true
      endpoint: mcp-collector.observability:4318
      insecure: true
      serviceName: context7-server
      metrics:
        enabled: true
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: grafana
  namespace: toolhive-system
  labels:
    demo.toolhive.stacklok.dev/vmcp-backend: "true"
spec:
  image: docker.io/grafana/mcp-grafana:0.11.0
  groupRef: demo-tools
  transport: streamable-http
  mcpPort: 8000
  proxyPort: 8080
  args:
    - --transport
    - streamable-http
  env:
    - name: GRAFANA_URL
      value: http://grafana.observability.svc.cluster.local
  telemetry:
    openTelemetry:
      enabled: true
      endpoint: mcp-collector.observability:4318
      insecure: true
      serviceName: grafana-server
      metrics:
        enabled: true
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPGroup
metadata:
  name: research-tools
  namespace: toolhive-system
spec:
  description: Group for vMCP research workflow tools
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: arxiv
  namespace: toolhive-system
  labels:
    demo.toolhive.stacklok.dev/vmcp-backend: "true"
spec:
  image: ghcr.io/stacklok/dockyard/uvx/arxiv-mcp-server:0.3.2
  groupRef: research-tools
  transport: stdio
  proxyPort: 8080
  proxyMode: streamable-http
  args:
    - --storage-path
    - /arxiv-papers
  podTemplateSpec:
    spec:
      volumes:
        - name: arxiv-papers
          emptyDir: {}
      containers:
        - name: mcp
          volumeMounts:
            - name: arxiv-papers
              mountPath: /arxiv-papers
  telemetry:
    openTelemetry:
      enabled: true
      endpoint: mcp-collector.observability:4318
      insecure: true
      serviceName: arxiv-server
      metrics:
        enabled: true
