---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-vmcp-client-secret
  namespace: toolhive-system
type: Opaque
stringData:
  client-secret: vmcp-secret-change-in-production
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: vmcp-authenticated
  namespace: toolhive-system
  annotations:
    toolhive.stacklok.dev/registry-export: "true"
    toolhive.stacklok.dev/registry-url: http://$MCP_HOSTNAME/vmcp-authenticated/mcp
    toolhive.stacklok.dev/registry-description: |
      Authenticated vMCP server with Keycloak OIDC authentication.
spec:
  groupRef:
    name: demo-tools
  incomingAuth:
    type: oidc
    oidcConfig:
      type: inline
      resourceUrl: http://$MCP_HOSTNAME/vmcp-authenticated/mcp
      inline:
        issuer: "http://$AUTH_HOSTNAME/realms/toolhive-demo"
        audience: "mcp-vmcp-authenticated"
        clientId: mcp-vmcp-authenticated
        jwksUrl: "http://$AUTH_HOSTNAME/realms/toolhive-demo/protocol/openid-connect/certs"
        insecureAllowHTTP: true
        jwksAllowPrivateIP: true
        protectedResourceAllowPrivateIP: true
        clientSecretRef:
          name: keycloak-vmcp-client-secret
          key: client-secret
  outgoingAuth:
    source: inline
  aggregation:
    conflictResolution: prefix
    conflictResolutionConfig:
      prefixFormat: "{workload}_"
  serviceType: ClusterIP
  telemetry:
    prometheus:
      enabled: true
  podTemplateSpec:
    spec:
      volumes:
        - name: keycloak-ca-cert
          secret:
            secretName: traefik-me-tls
            items:
              - key: ca.crt
                path: ca.crt
      containers:
        - name: vmcp
          volumeMounts:
            - name: keycloak-ca-cert
              mountPath: /etc/ssl/certs/keycloak-ca
              readOnly: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vmcp-authenticated-route
  namespace: toolhive-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /vmcp-authenticated
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: vmcp-vmcp-authenticated
          port: 4483
    - matches:
        - path:
            type: Exact
            value: /.well-known/oauth-protected-resource/vmcp-authenticated/mcp
      backendRefs:
        - name: vmcp-vmcp-authenticated
          port: 4483
